id: EAtfoZu0Y3nqXLeD
name: Бензопила
rarity: blue
tags:
  - кровь
  - сталь
description: Один раз в ход, когда вы попадаете атакой по цели, у которой меньше половины ПЗ, она получает дополнительно {damage}. Активируйте навык, чтобы бросить урон.
activation: special
trigger:
  on: damage_roll
  when: [attack_only, target_bloodied]
  bonus: { from: damage }
uses: 1
recovery: turn
damage:
  - formula: 1d6
    type: slashing
ranks:
  - text: Дополнительный урон — {damage}.
    damage:
      - formula: 1d8
        type: slashing
  - text: Дополнительный урон — {damage}.
    damage:
      - formula: 1d10
        type: slashing
